version: '3.8'

services:
  postgres:
    image: postgres:14
    restart: always
    ports:
      - "5432:5432"
    environment:
      - DATABASE_HOST=localhost
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=postgres
    container_name: postgresql
    volumes:
      - db_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "85:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: "ceo@creativa.dev"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    container_name: pgadmin4
    volumes:
      - dpage_data:/var/lib/pgadmin
    depends_on:
      - postgres

volumes:
  db_data:
  dpage_data: